module:
  block: -5
  block_content: 0
  book: 0
  breakpoint: 0
  ckeditor: 0
  color: 0
  comment: 0
  config: 0
  contact: 0
  contextual: 0
  datetime: 0
  dblog: 0
  devel: 0
  devel_generate: 0
  editor: 0
  entity_reference: 0
  examples: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  forum: 0
  help: 0
  history: 0
  image: 0
  kint: 0
  language: 0
  locale: 0
  menu_link_content: 0
  menu_ui: 0
  migrate: 0
  migrate_drupal: 0
  node: 0
  options: 0
  path: 0
  quickedit: 0
  rdf: 0
  search: 0
  shortcut: 0
  system: 0
  taxonomy: 0
  telephone: 0
  text: 0
  toolbar: 0
  tour: 0
  update: 0
  user: 0
  views_ui: 0
  views: 10
theme:
  seven: 0
  bartik: 0
